### ISSUE TITLE
Create bower packages for each individual web component

### ISSUE THREAD

**Issue by ccmitchellusa** [ibm-js/deliteful#184]
Kitchen-sink/all-in-one pre-built packages in bower make getting started and basic tutorials/samples simpler, because lower level dependency details around which specific components within the package are being used; however, this comes at a cost in project footprint because all components are always included.  

This is ok for the basic cases, but it would be an extremely rare case that an application makes use of all web components in deliteful in a single app.  There more common use cases were someone only will want a single web component for their website or mobile app, and there is also the production use case, where deployed applications should only contain the code they require and no more.

Rather than the current kitchen sink packaging of delite widgets, we should provide individual pre-built packages in bower (with simple defaulted features for things that have lots of potential flexibility like stores) for each web component, for example, "deliteful-LayoutContainer", "deliteful-ProgressBar", etc. 

We should also consider refactoring deliteful components, putting each into their own self-contained repository, similar to what has been done in the Polymer project, but that can be discussed under a separate ticket.

**Comment by cjolif** [comment]
As we now have made progress, it is time to revisit this and see how at least some of the deliteful widgets can be bower enabled separately.

**Comment by edchat** [comment]
Hi, 
   After talking to chrism and clmath, I decided to try to setup some tests to see if I could make some progress on this.  With help from clmath I was able to update the build/Gruntfile.js here https://github.com/edchat/sdk-utils/blob/widgetBuild/build/Gruntfile.js#L106-L126 to create a `deliteful-StarRating-build`, a `deliteful-Checkbox-build` and a `deliteful-Combobox-build`.  You can see them here: 
```
https://github.com/edchat/deliteful-StarRating-build
https://github.com/edchat/deliteful-Checkbox-build
https://github.com/edchat/deliteful-Combobox-build
```

They can be installed with bower, for now with the git repo:
```
bower install "https://github.com/edchat/deliteful-StarRating-build.git"
bower install "https://github.com/edchat/deliteful-Checkbox-build.git"
bower install "https://github.com/edchat/deliteful-Combobox-build.git"
```
And each widget can be loaded by a script tag:
`<script src="bower_components/deliteful-Combobox-build/layer.js"></script>`
Or by wrapping the require for the widget in a require for the layer:
```
require(["deliteful-Combobox-build/layer"], function() {
    require(["app/main", "deliteful/Combobox"], function() {
        ...
    });
});
```
I think this is a good start for this work, but there are a couple of things we may want to consider.
1) Should we try to create a delite-dependency layer which could be used by all of the widgets to avoid having those dependencies built into each widget's layer to avoid the duplication when more than one widget is used?  
2) Should we try to include the samples for the widget in the deliteful-widget-build to have the sample available when the widget is installed with bower?

Just a note about the manual steps taken to get the build output for the individual widgets into the git projects, the build will create the folders with a double `-build` like:
``` 
deliteful-StarRating-build-build
```
And the contents of that folder is copied into the git project (without the double `-build`):
```
deliteful-StarRating-build
```

**Comment by cjolif** [comment]
another point is what about getting source versions? In real app development you often end up creating your own JavaScript layers. For that purpose it is often easier to start back from source.

**Comment by edchat** [comment]
@cjolif, you are right.  I should have mentioned that my first look at this involved trying to set it up as a git project with the source for just the widget, which would allow the user to pull the source for the individual widget and build it himself.  The problem I ran into with that approach was that I could not find a way (other than duplicating the widget code) to link the code for the widget from deliteful into the widget project.  So if we really want to do that we would probably have to move the code for each widget into it's own git project and then set those up as submodules (or subtrees) in deliteful.  At this point I don't think it is worth it to take that step, but others may disagree.

My suggestion would be to make the built versions available, but to have instructions that tell them that if they are going to be doing their own build they should use deliteful directly rather than the individual built widgets.

Another possibility would be to setup a yoman generator for this to ask if they want the source or built version and perhaps which widgets they are interested in.

**Comment by ccmitchellusa** [comment]
There is already the ability to do optimized/advanced builds with source.  The ux problem that needs to be solved is how can one very easily grab a default configuration of any one of the components and begin using the component in an html doc (without having to go through advanced build steps).  What Ed has done is almost there, but we should consider having each widget's bower package also pull the prebuilt delite prereq package from bower, rather than building a copy of delite into each component package.  delite should be a black-box library from the component's perspective.  I like how Ed has provided a script for each component that hides the nested require ugliness from new users.
The docs page for each component (http://ibm-js.github.io/deliteful/docs/0.6.0/index.html) should be updated to have a section showing the simplest getting started use case, but with a caveat about when you begin to use many customized deliteful web components within the same page, you will want to do an optimized build from source code, with a link to the docs showing how to do the more advanced builds from source.

**Comment by ccmitchellusa** [comment]
also, the kitchen-sink prebuilt deliteful approach used but the tutorial still makes sense, I would still provide the kitchen sink version of deliteful via bower for sample apps that use many components.  The new approach above allows people to just use one or two components from delightful (and not incur the full performance impact of kitchensink).

**Comment by wkeese** [comment]
> The ux problem that needs to be solved is how can one very easily grab a default configuration of any one of the components and begin using the component in an html doc (without having to go through advanced build steps).

I just wanted to point out that you can already do that, simply by downloading the deliteful source (`bower install deliteful`) and using the component(s) you want.   No build necessary.   Running against source is even easier than using pre-built code because you don't need nested `require()` calls. 

And on the flip side, the only way to get optimal performance is to do a custom build.

So, ISTM you are looking for some middle-ground approach that's faster than running against source, albeit not as fast as a custom build, and is easier than doing a custom build, albeit slightly harder than running against source.

**Comment by edchat** [comment]
I have updated my deliteful-StarRating-build, deliteful-Combobox-build, and deliteful-Checkbox-build to use a new delite-fullBuild (https://github.com/edchat/delite-fullBuild) as a dependency.  
Here are the links to the projects, 
https://github.com/edchat/deliteful-StarRating-build
https://github.com/edchat/deliteful-Checkbox-build
https://github.com/edchat/deliteful-Combobox-build
They can be installed with bower, for now with the git repo:
```
bower install "https://github.com/edchat/deliteful-StarRating-build.git"
bower install "https://github.com/edchat/deliteful-Checkbox-build.git"
bower install "https://github.com/edchat/deliteful-Combobox-build.git"
```
And each widget can be loaded by a script tags like this:
```
<script src="bower_components/delite-fullBuild/fullBuild.js"></script>
<script src="bower_components/deliteful-StarRating-build/layer.js"></script>
```
Or by wrapping the require for the widget in a require for the delite-fullBuild and the layer:
```
require(["delite-fullBuild/fullBuild", "deliteful-StarRating-build/layer"], function() {
    require(["app/main", "deliteful/Combobox"], function() {
        ...
    });
});
```
So this is nice in that if multiple widgets are used only the delite-fullBuild is only requested once, but it does add a second script tag or the addition of the delite-fullBuild to the require which adds some complexity.

I hope these 3 widgets are enough for us to evaluate whether or not this is helpful.
As Bill said this is adding some complexity with the use of the widget compared to using the source.

ISTM that we may be better off using a full built version of deliteful as the simple option to add a widget to an app instead of doing this for every widget.  If we use https://github.com/ibm-js/deliteful-build they still have to use the extra require for the "deliteful-build/layer" but it is ready to use now, and the built layer is only 115K.

**Comment by edchat** [comment]
I want to leave a comment here with the current state of this work.
You can see my changes to the sdk-utils (build) here:
https://github.com/cjolif/sdk-utils/compare/master...edchat:widgetBuild
With this change, to build the widgets, after the build setup for the normal build (npm install etc)
run:
grunt widgetOnlyBuild -v -f
That will create these folders under the build folder with the contents to be used in the git projects of the same name:
deliteful-StarRating-build
deliteful-Checkbox-build
deliteful-Combobox-build
deliteful-RadioButton-build
Here are the links to the temporary projects in my github,
https://github.com/edchat/deliteful-StarRating-build
https://github.com/edchat/deliteful-Checkbox-build
https://github.com/edchat/deliteful-Combobox-build
I did not create the repo for deliteful-RadioButton-build.

**Comment by wkeese** [comment]
No plans to do this.
