### ISSUE TITLE
Switch: checked property not up to date when change callback is called

### ISSUE THREAD

**Issue by edurocher** [ibm-js/deliteful#285]
When the change callback is called, the checked property seems to be the old value instead of the new value. This makes it hard to code the callback function correctly.

**Comment by wkeese** [comment]
Note that that Firefox now behaves like Chrome, with "click" then "change" , as per the W3 recommendation (see https://stackoverflow.com/questions/25014911/is-there-a-standard-for-the-event-order-of-click-and-change-on-a-checkbox).    However, IE11 and Edge do the opposite.

A related issue is that the "checked" and "changed" events are emitted from the nested <input> rather than the Checkbox itself.
