### ISSUE TITLE
Checkbox and RadioButton labeling should be easier

### ISSUE THREAD

**Issue by dmandrioli** [ibm-js/deliteful#442]
If you just drop some checkboxes and radiobuttons with default configuration, you get something like
![image](https://cloud.githubusercontent.com/assets/1109677/5631339/175c4348-95c6-11e4-9594-47378c194da7.png)
Source: http://jsfiddle.net/ibmjs/c3kgt98w/

Labels alignment is weird and different between the two widgets:
 -  Checkbox label is too high, the text baseline should be aligned with the bottom of the square
 - Radio label is too low
 - Checkboxes and Radiobuttons should be aligned

As an example, here is what you get using Bootstrap
![image](https://cloud.githubusercontent.com/assets/1109677/5631445/e78a623e-95c6-11e4-83ba-97e79d493e8d.png)

**Comment by tkrugg** [comment]
I've been working on this, as part of issues https://github.com/ibm-js/deliteful/issues/299#issuecomment-64398124 and https://github.com/ibm-js/deliteful/pull/415

I fixed the outline, but also the alignement on radio buttons.
i'm about to send a [PR](https://github.com/tkrugg/deliteful/compare/RadioButton/fixing-style) but I need to work on it some more, even maybe include the fix for checkbox.

**Comment by AdrianVasiliu** [comment]
Just to mention that adding vertical-align: middle to d-radio-button gives this result with your jsfiddle:

![image](https://cloud.githubusercontent.com/assets/1583981/5632426/eb7f7c0a-95ce-11e4-9afb-57c1d67f7a68.png)

**Comment by wkeese** [comment]
Also fixed by 4dfd44b8f5bb91ef27a66ddff4f688c7135ca1f3.
