### ISSUE TITLE
Theming: how an application developer can easily derive from one of our theme and provide its own theme to be used by the application

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#457]
One of the requirement is that ideally he does not need to force modifying original deliteful & delite distribution.

**Comment by tkrugg** [comment]
Here is what we've got so far:

When developers generate a deliteful app with yoeman, they get:
- a `bower_components/` folder
- a `mytheme/` folder structured exactly like `bower_components`, containing the .css files for our theme (see original issue for more details https://github.com/ibm-js/delite/issues/328#issue-47739695)

To ask requirejs to go get the css files from `mytheme/` rather than `bower_components/`, they'll need to declare a path "theme" .

```js
require.config({
    baseUrl: "bower_components",
    paths: {
        "js": "../js",
        "theme" : "../mytheme"
    }
});
```

then requirejs-dplugin/css checks if this `theme` has been defined and makes the switch.

I'd like to know what you guys think about this. using paths is somehow comfortable since it leverages a lot of the work to requirejs.  It's also quite natural if you think of paths as where the user links to his own stuff (own "js" scripts, own "theme/"). But it's also polluting the path space.

**Comment by wkeese** [comment]
Hmm, does that really work?   I thought that `paths` was for specifying the location of packages, i.e. top level directories like "delite" and "deliteful".  `themes` is a subdirectory of deliteful (and in the future there could be other packages with a theme directory too).

You might be able to use `map` but IIRC you would need to setup a separate mapping for each widget.   So that's not a nice API.

There's also a `themeMap` configration setting for the `theme!` plugin, but that (currently) will just redirect from (for example) deliteful/StarRating/themes/bootstrap to deliteful/StarRating/themes/mytheme.

**Comment by cjolif** [comment]
I think this works because @tkrugg is "abusing" path (i.e. in requirejs-dplugins) if `theme` path is defined he is changing the path of the loaded resource to start with `theme` and then requirejs is doing the remapping. Even if that does solve the problem I must admit I'm skeptical about the cleaness of this solution.

**Comment by wkeese** [comment]
Hmm, still not sure I follow (although I did reread ibm-js/delite#328).  Which code in requirejs-dplugins are you talking about, perhaps the css plugin?

**Comment by cjolif** [comment]
actually I'm not sure this is either indeed requirejs-dplugins/css or delite/theme. @tkrugg ?

**Comment by tkrugg** [comment]
it's requirejs-dplugins/css, I didn't need to touch delite/theme

**Comment by wkeese** [comment]
I see.   I'm interested to see what you did in there.   Your first comment in this ticket though seems incomplete.   Doesn't the `require.config()` call also need to specify configuration options for the CSS plugin, to tell it how to do the remapping?

**Comment by tkrugg** [comment]
I posted the changed [requirejs-dplugin/css.js](https://gist.github.com/tkrugg/88c9faa8e810bb4fba42#file-requirejs-dplugin-css-js-L103) so you can see what it does .

**Comment by wkeese** [comment]
OK, thanks.  My thoughts are:

1) it's kind of weird to have such specific code in the CSS plugin; if anywherem I would have expected the code to be in the theme! plugin
2) the path transformation is currently very hardcoded; i was thinking of specifying a module configuration option to do a regex replacement (or list of regex replacements).   mapping `^` to `theme/` could of course be one such replacement.

**Comment by wkeese** [comment]
Closing this as we don't have any current plans to support it.
