### ISSUE TITLE
remove calls to parse() and attachedCallback() from samples, tests

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#541]
The sample files no longer need to call `parse()`.  As a corollary, most of them don't need to `require()` `"delite/register"` explicitly anymore either.

The functional tests should call `register.deliver()` rather than `register.parse()`.   The `deliver()` call is only necessary so that the `ready` flag doesn't get set prematurely.

**Comment by EAlexRojas** [comment]
When testing this changes I found a problem using the latest version of dcl (1.1.3).
On IE11 none of the samples/test works due to a change introduced in that dcl version. 
I created an issue against dcl to report the problem: 
[https://github.com/uhop/dcl/issues/18 ](https://github.com/uhop/dcl/issues/18)

**Comment by AdrianVasiliu** [comment]
In the Combobox unit test, 9e32a0e8f2e13c765252268d9bd8241d093558e3 replaced `register.parse(container);` by `register.deliver();`. Apparently, this change has something to do with the new errors that appeared for IE10 in the travis build (there used to be no error in the unit test):

```
STARTED  Test 'main - deliteful/Combobox: markup - Store.add/remove/put (custom element store)' 
on internet explorer 10 on WINDOWS:
undefined: Unable to get property 'nodeType' of undefined or null reference
TypeError: Unable to get property 'nodeType' of undefined or null reference
  at getEnclosingWidget  <delite/Widget.js:296:5>
  at getParent  <delite/Widget.js:226:4>
  at attachedCallback  <deliteful/list/ItemRenderer.js:25:17>
  at Anonymous function  <delite/register.js:372:16>
  at f  <dcl/advise.js:72:36>
  at upgrade  <delite/register.js:137:6>
  at Anonymous function  <delite/register.js:499:7>
  at processMutations  <delite/register.js:493:4>
  at deliver  <delite/register.js:536:5>
  at beforeEach  <deliteful/tests/unit/Combobox.js:281:4>
```
(https://travis-ci.org/ibm-js/deliteful/builds/59724806).

The direct cause of the error is that Widget.getParent() now gets called for a widget which, on IE10, is not (yet?) in the DOM. Thus, the implementation of Widget.getParent() (`return this.getEnclosingWidget(this.parentNode);`) calls Widget.getEnclosingWidget with a null argument, which is not expected by getEnclosingWidget()... 
@wkeese, shouldn't Widget.getEnclosingWidget() do something like `return this.parentNode ? this.getEnclosingWidget(this.parentNode) : null;` ?

This would hold for the direct cause of the test error. Now, I don't know if changing Widget.getEnclosingWidget() to support the call for widgets not in the DOM is enough for fixing the test failure. @EAlexRojas, could you please double-check this part of your 9e32a0e8f2e13c765252268d9bd8241d093558e3?

**Comment by wkeese** [comment]
> @wkeese, shouldn't Widget.getEnclosingWidget() do something like return this.parentNode ? this.getEnclosingWidget(this.parentNode) : null; ?

That wouldn't help because `ItemRenderer#attachedCallback()` (rightfully) expects `getParent()`  to return a non-null value:

```js
if (this.getParent().getAttribute("role") === "grid") {
```

The real question is why `ItemRenderer#attachedCallback()` is called when the ItemRenderer isn't attached (or is no longer attached) to the document.  I can't reproduce this error locally, or even from running `grunt test:remote`, so it's hard to debug.  But I suspect it's from a race condition on an ItemRenderer that was quickly added and then removed from the document.   The ItemRenderer might have been created from a previous test (i.e. the createCombobox() call that runs before the "Store.add/remove/put" test) rather than the test getting the failure.

I suppose there's a race condition in delite/register where it doesn't properly handle nodes that were attached then quickly detached from the document, before the timer fires.  Not sure if that's the cause of this failure or not.  I noticed that `ItemRenderer#attachedCallback()` is sometimes called on the timer (the `schedule()` call in delite/register).   That happens when the `<d-list>` is in a `<div class="d-popup">` attached to `<body>`, presumably due to the dijit/popup code showing/hiding the popup, which triggers the call to attachedCallback().

I'll investigate things on the delite side.

**Comment by AdrianVasiliu** [comment]
> That wouldn't help

Okay, but still, is it normal that Widget.getParent() throws an error instead of returning a meaningful value (`null`) when there's no parent? 

> The ItemRenderer might have been created from a previous test [...]. That happens when the `<d-list>` is in a `<div class="d-popup">` attached to `<body>`, presumably due to the dijit/popup code showing/hiding the popup

Might be indeed. Combos are added to `container`, and the cleanup of test cases relies on `container.parentNode.removeChild(container);` in `afterEach()`. We need a safe way to remove HasDropDown widgets including their popup.

> I'll investigate things on the delite side.

Thanks.

**Comment by wkeese** [comment]
I suppose it would be better to return null.

**Comment by EAlexRojas** [comment]
@AdrianVasiliu I ran those unit tests locally and using remote tests and they all pass, I don't have that error.

**Comment by AdrianVasiliu** [comment]
@EAlexRojas As @wkeese said, this error can be due to a race condition. In any case, it does hurt *on IE 10* in the travis builds after the removal of register.parse() (9e32a0e8f2e13c765252268d9bd8241d093558e3).

BTW, it might hurt only when running the entire suite, not the Combobox test separately - @wkeese, I wonder if the "faulty" ItemRenderer for which we get the error couldn't be from a previous test (not testcase).

On my side, trying to run locally the entire deliteful suite in IE11, it seems to freeze after the test of ViewStack... And if I set IE11 in IE10 emulation mode, I get

![image](https://cloud.githubusercontent.com/assets/1583981/7315808/52c3ce06-ea71-11e4-80ec-e35317d2f98b.png)
![image](https://cloud.githubusercontent.com/assets/1583981/7315811/56b8fb4e-ea71-11e4-8b53-88733c589432.png)

(with an updated dpointer 0.5.0, and with master versions of decor/delite/deliteful), then the same freeze... Not sure what's happening, anyway...

**Comment by AdrianVasiliu** [comment]
And be aware that, when running locally, some tests may fail if you move the mouse, change focus etc.

**Comment by wkeese** [comment]
I fixed the Combobox unit test failure with a bunch of commits to delite, in particular ibm-js/delite#bccb2d52bc63d54351e25cf132261b885d94b2ba.   Maybe it fixed the IE10 problem too.  Not sure.

**Comment by edchat** [comment]
Thanks wkeese.  I think we are done with the tests and samples.

**Comment by AdrianVasiliu** [comment]
@wkeese:
> Maybe it fixed the IE10 problem too.

Yes, it did fix the Combobox/IE10 problem (https://travis-ci.org/ibm-js/deliteful/builds/60367872).

**Comment by AdrianVasiliu** [comment]
BTW, thanks @wkeese!
