### ISSUE TITLE
Regression on PageableList

### ISSUE THREAD

**Issue by harbalk** [ibm-js/deliteful#565]
An error " Cannot read property 'fetchRange' of null " appears when using PageableList.

It is because the property '_collection' of the list is not yet loaded when the _loadNextPage() is called by the refreshRendering() function.

The problem is linked with the two following issues : https://github.com/ibm-js/deliteful/issues/539#issuecomment-89227088 and https://github.com/ibm-js/deliteful/issues/538.

Now the 'this.attached' condition has been totally removed so we passed in the "initial loading if" directly when the 'store' is modified. It is a problem because the '_collection' is still null. And the _loadNextPage() use this '_collection'.

```
	        refreshRendering: function (props) {
			if (this.pageLength > 0) {
				if ("store" in props || "query" in props || "_collection" in props)  {
					// Initial loading of the list
                                        ...
                                        this._loadNextPage()
```

I think the best solution is to remove the " 'store' in props " condition in the if of initial loading as I said in https://github.com/ibm-js/deliteful/issues/538 . I do not think it will have another impact beside this one.

You can reproduce the error when loading one of the deliteful/tests/functionnal/list/pageable-prog-X.html .

@wkeese , @edchat what do you think about it ?

**Comment by wkeese** [comment]
I guess you are right.   Looking quickly at the code, it seems like all you need is:

```js
if ("_collection" in props)
```

because `_collection` represents the data to be displayed, so ultimately that's the only thing that directly affects the displayed data.

Presumably there's other code somewhere that will requery the store and thus reset `_collection` when `store` or `query` are changed?  I don't understand how the current code works, because it looks like the only code that sets `this._collection` is `processCollection()`, and AFAICT that method is never called.  What am I missing?

**Comment by harbalk** [comment]
The function processCollection() is called by the function queryStoreAndInitItems() in delite/Store.js which is itself called by the function computeProperties of delite/Store.js.
computeProperties() effectively execute queryStoreAndInitItems() when query of store are in the props list.
I don't know if it's answer you question ?

**Comment by wkeese** [comment]
Ah thanks, I got confused because the code is in delite rather than deliteful.

So, as I suspected, if either `store` or `query` are changed then `Store#computeProperties()` will trigger an update to `_collection`, so I guess `PageableList#refreshRendering()` only needs to listen for changes to `_collection`.
