### ISSUE TITLE
How is the deliteful layer built?

### ISSUE THREAD

**Issue by schmigware** [ibm-js/deliteful#572]
Please excuse my question, I am new to ibm-js, deliteful, amdbuild, etc.

It is my understanding that in order to build out layer files using ibm-js amdbuild, I must provide some initial set of 'requires' in order for the tooling to deduce a dependency graph. 

I do not see any such 'entry point' in deliteful, which I would expect to be the case, given it is a library. Nor do I see any use of amdbuild in the associated Gruntfile.js. I expect the yeoman generator is used for this?

So my question is, how is the deliteful layer built?

Many thanks.

**Comment by clmath** [comment]
The deliteful layer is made with [ibm-js/grunt-amd-build](https://github.com/ibm-js/grunt-amd-build) and the gruntfile located here: https://github.com/cjolif/sdk-utils/tree/master/build

This gruntfile is very long because it contains the layer definition of several ibm-js projects and configuration for various other tasks which are ibm-js specific. Those tasks are [here](https://github.com/cjolif/sdk-utils/tree/master/build/tasks) and are a good example of how you can customize your build to suit your needs.

As you mention there is no entry point in deliteful so we use globbing patterns to add all the deliteful modules in the initial set of "requires".

I hope this answer your question.

**Comment by schmigware** [comment]
Yes, thank you - I could not see such a file in the projects I looked at, and needed to verify that this approach is necessary for "library" AMD builds such as deliteful.

Much appreciated.

**Comment by cjolif** [comment]
By the way, for that type of questions I guess the forum here: http://ibm-js.github.io/delite/community.html is a better option than github issues.

**Comment by schmigware** [comment]
Duly noted, thanks again.
