### ISSUE TITLE
Accordion: addChild(), removeChild() broken.

### ISSUE THREAD

**Issue by xblox** [ibm-js/deliteful#645]
I think there is a bug in Accordion#removeChild(panel). It removes the panel but not the AccordionHeader.

The other thing is : Accordion#onAddChild  is never called (programmatically created) and so new added panels won't get properly initiated with a AccordionHeader. I can't recall exactly how my Maqetta clone did de-serialize the widget's children but after debugging I figured that the most is done in the Accordion#createdCallback and at the time this is called, the accordion is still empty and the panels are added later for some reason by Maqetta. I couldn't find a widget API method to refresh rendering in this case (init unparsed children). 

Is it possible i have to this manually just ? I noticed already that Deliteful works well if used the declarative way but when using it programmatically I have lots weird things going on (just saying)

well, close this just if its out of scope for you but it would great to get some little feedback on this, possibly I am doing things wrong (have similar problems with ViewStack)

**Comment by wkeese** [comment]
Yup, sorry, those things should work but looks like I didn't implement them, at least not after I rewrote Accordion.   Not sure if they used to work or not.

The Accordion programmatic test (tests/unit/Accordion) is also bad because it's obviously missing tests for this case.  It doesn't check for incrementally adding/removing panes after Accordion creation.

**Comment by gbaumgart** [comment]
vale, ok, good to know. got it working after all for me but too naive to make it into a lib.
however, just wanted to let you know.
thanks Bill again.
g

**Comment by xblox** [comment]
thanks Bill!
