### ISSUE TITLE
List should emit `delite-size-change` every time its content changes.

### ISSUE THREAD

**Issue by brunano21** [ibm-js/deliteful#653]
With the current implementation, `List` emits a `delite-size-change` event when `this.renderItems` changes. However this is not enough and does not cover all scenarios. 
In fact, the event should be emitted every time the list's content changes, including when displaying the NoItems node and the LoadingPanel node.

`List#refreshRendering()` should be rearranged like below (`deliteful/list/List.js`):

```
refreshRendering(props) {
    ...
    if (("renderItems" in props && this.renderItems) ||
        ("_displayedPanel" in props && this._displayedPanel !== props._displayedPanel)) {
        // notify the list content changed.
        this.emit("delite-size-change");
    }
    ...
}
```

**Comment by wkeese** [comment]
Agreed that it should also emit that event when the displayed panel changes.

Checking for things like `this._displayedPanel !== props._displayedPanel` is a bit weird since the whole point of `props` is to only list the properties that have changed value.  Is the `this._displayedPanel !== props._displayedPanel` code to avoid the special case on widget initialization when `refreshRendering()` is called for every property?   If so, maybe using the `isAfterInitialRendering` parameter makes more sense:

```js
/**
 * Callback function to render UI upon property changes.
 * @param {Object} oldValues The hash table of old property values, keyed by property names.
 * @param {boolean} isAfterInitialRendering True if this call is right after `initializeRendering()`.
 */
refreshRendering: function () {}
```

It amounts to the same thing; just a style issue.

**Comment by brunano21** [comment]
Actually the check I did was meant to be in that way, `this._displayedPanel !== props._displayedPanel`. In fact as you said, `props` brings all those properties that have changed. If `_displayedPanel` value changed, this means that the popup is going to contains something that could not fit properly, so the `delite-size-change` event should be fired.

Or do you see a different way to know when the `_displayedPanel` value changed?

**Comment by wkeese** [comment]
How about `"_displayedPanel" in props && !isAfterInitialRendering`?   Sounds like you don't think that works.  What case do you think it fails in?
